### ISSUE TITLE
No connection to localhost

### ISSUE THREAD

**Issue by lonesomewalker** [greenstatic/bigbluebutton-exporter#29]
How to debug, if a server doesn't show the stats?
Done everything from: /installation/all_in_one_monitoring_stack/
On every other server no issues, but on one server there is no access to the current data.
API works well, queries do show the right values.

In Grafana, Prometheus is added with localhost, but in the dashboard, no localhost is shown.

**Comment by greenstatic** [comment]
> API works well, queries do show the right values.

Which queries? Are you talking about the Grafana -> Prometheus queries or the metrics that the exporter collects (by accessing the exporters metrics page directly)?

> On every other server
If you have multiple servers it is recommended to have a single Prometheus and Grafana installation so that you can have all the dashboards in one place and so you have the all servers dashboard show metrics for all servers in one place.

**Comment by lonesomewalker** [comment]
Hi :-)
No, all servers are single servers.
On every other server, the statistics are collected perfectly.

Only on one server i get N/A, even the exporter version is not shown.

Seems like a docker/network issue?

**Comment by greenstatic** [comment]
Do you have any entries if you select `instance` in the top left hand corner?

**Comment by lonesomewalker** [comment]
No, and therefore i think this might be the culprit :-)
On all other servers, there is localhost.

**Comment by greenstatic** [comment]
I just updated the docs with some tips regarding debugging: https://bigbluebutton-exporter.greenstatic.dev/debugging/#debugging-all-in-one-monitoring-stack

**Comment by lonesomewalker** [comment]
Already have DEBUG=true, stdout is empty. :-(

**Comment by lonesomewalker** [comment]
Whoa, NOW we have some stuff :-)

> docker-compose logs bbb-exporter

`bbb-exporter     | 2020-05-15 21:43:21,162 [DEBUG]: Calculating room participants histogram
bbb-exporter     | 2020-05-15 21:43:21,168 [DEBUG]: Calculating room listeners histogram
bbb-exporter     | 2020-05-15 21:43:21,168 [DEBUG]: Calculating room voice participants histogram
bbb-exporter     | 2020-05-15 21:43:21,168 [DEBUG]: Calculating room video participants histogram
bbb-exporter     | 2020-05-15 21:43:21,169 [INFO]: Finished collecting metrics from BigBlueButton API
bbb-exporter     | ----------------------------------------
bbb-exporter     | Exception happened during processing of request from ('127.0.0.1', 49478)
bbb-exporter     | Traceback (most recent call last):
bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
bbb-exporter     |     self.finish_request(request, client_address)
bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
bbb-exporter     |     self.RequestHandlerClass(request, client_address, self)
bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
bbb-exporter     |     self.handle()
bbb-exporter     |   File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
bbb-exporter     |     self.handle_one_request()
bbb-exporter     |   File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
bbb-exporter     |     method()
bbb-exporter     |   File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 159, in do_GET
bbb-exporter     |     self.wfile.write(output)
bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
bbb-exporter     |     self._sock.sendall(b)
bbb-exporter     | BrokenPipeError: [Errno 32] Broken pipe
bbb-exporter     | ----------------------------------------
bbb-exporter     | 2020-05-15 21:43:24,165 [DEBUG]: https://bbb.server.tld:443 "GET /bigbluebutton/api/getRecordings?checksum=xxxxxxxxxxxx&state=processing HTTP/1.1" 200 None
bbb-exporter     | 2020-05-15 21:43:24,166 [DEBUG]: Requesting via API recordings processed data
bbb-exporter     | 2020-05-15 21:43:24,168 [DEBUG]: Starting new HTTPS connection (1): bbb.server.tld:443
`

> docker-compose logs grafana

`grafana          | t=2020-05-15T21:22:27+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=xxx::xxx::xxx referer="https://bbb.server.tld/monitoring/d/HIbd_CXZz2/bigbluebutton-server-instance-netdata?orgId=1&refresh=5s" error="http: proxy error: context canceled"
grafana          | t=2020-05-15T21:22:27+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=xxx::xxx::xxx time_ms=5 size=0 referer="https://bbb.server.tld/monitoring/d/HIbd_CXZz2/bigbluebutton-server-instance-netdata?orgId=1&refresh=5s"
grafana          | t=2020-05-15T21:22:27+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=xxx::xxx::xxx referer="https://bbb.server.tld/monitoring/d/HIbd_CXZz2/bigbluebutton-server-instance-netdata?orgId=1&refresh=5s" error="http: proxy error: context canceled"
grafana          | t=2020-05-15T21:22:27+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=xxx::xxx::xxx time_ms=5 size=0 referer="https://bbb.server.tld/monitoring/d/HIbd_CXZz2/bigbluebutton-server-instance-netdata?orgId=1&refresh=5s"`

**Comment by greenstatic** [comment]
This is a strange error. Try to delete all the containers and start them again:
```shell
sudo docker-compose down -v
sudo docker-compose up -d
```

**Comment by lonesomewalker** [comment]
Yes, indeed.
Already tried to forward 9090 to localhost as suggested -> no Prometheus shown.

Already tried to delete the containers -> still not working.

**Comment by greenstatic** [comment]
Are you sure Prometheus is running?
```shell
sudo docker ps
```
What is the "status"? What do the logs say (of the Prometheus container)?

**Comment by lonesomewalker** [comment]
> docker ps

`CONTAINER ID        IMAGE                                       COMMAND                  CREATED              STATUS              PORTS                      NAMES
3f92c4696d25        greenstatic/bigbluebutton-exporter:v0.3.0   "python server.py"       About a minute ago   Up About a minute                              bbb-exporter
5351d4558cc2        prom/node-exporter:v0.18.1                  "/bin/node_exporter …"   About a minute ago   Up About a minute                              node_exporter
5da79f26f9a5        prom/prometheus:v2.17.2                     "/bin/prometheus --c…"   About a minute ago   Up About a minute                              prometheus
d61869ac6bb6        grafana/grafana:6.7.1                       "/run.sh"                About a minute ago   Up About a minute                              grafana
70c1dfaa14ae        bigbluebutton/greenlight:v2                 "bin/start"              24 hours ago         Up 24 hours         127.0.0.1:5000->80/tcp     greenlight-v2
581c00193531        postgres:9.5                                "docker-entrypoint.s…"   24 hours ago         Up 24 hours         127.0.0.1:5432->5432/tcp   greenlight_db_1`

This becomes REALLY strange now...

When re-installing the docker container, if i am fast enough, i get API information and also BBB-Exporter says 0.3.0, but just seconds later -> N/A

The strange point is: this machine is the same setup as every other BBB server i did.
If there would be some special configuration or at least something different... but this is exactly the same scripted setup.

**Comment by greenstatic** [comment]
Can you please edit your `docker ps` output with a multi-line code snippet (three backticks `) https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by lonesomewalker** [comment]
Sorry :-| done.

**Comment by greenstatic** [comment]
You don't need to place your entire comment into a code snippet :stuck_out_tongue: 

Are you sure you cannot connect (using SSH local port forward) to the Prometheus container?

**Comment by lonesomewalker** [comment]
I didn't -> Github bug ;-)

![github-bug](https://user-images.githubusercontent.com/856110/82132251-0f183500-97de-11ea-90ac-2197b4007e7d.jpg)

Yes, i tried to port 9090, as you wrote on your debug page.
This means for me: issues with Prometheus, right?
But even after deleting the docker container, and reinstalling it, as written: for a short period (like 5 seconds) i get stats. Then no input.
netstat also says, only docker is listening to port 9090 :-(

**Comment by greenstatic** [comment]
Hmm strange (regarding the backticks and your problem) :stuck_out_tongue: 
1. Usually with mutli-line code snippet you leave the first and last line with backticks empty
\`\`\`
<code\>
\`\`\`

2. Can you try connecting to an instance that "works", just to cross out that you are not connecting via SSH wrong.

3. Are you sure you have the correct docker-compose file?

**Comment by lonesomewalker** [comment]
:-D i agree, after adding a new line, now the comment is correct.

Yes, i already tried this with several other instances, i also copied over the compose file.

What makes me wonder: why can i see the first seconds, and then it becomes "no data"?

**Comment by lonesomewalker** [comment]
O M G

If somebody will ever get in this situation: check your ip settings.
In this case, the hosting did not set IPv6 correctly...

Now everything works smooth as it should.

Thanks for your effort!

**Comment by greenstatic** [comment]
I don't follow exactly, Prometheus was binded to 127.0.0.1 (IPv4) and the debug instructions were also IPv4. So you should have been able to connect to Prometheus.

I understand however localhost (which resolved to ::1) in Grafana and why it couln't connect to Prometheus.

**Comment by Kelivan** [comment]
I setup all_in_one_monitoring_stack and I have the same picture "No Data".
In bbb-exporter logs:
> bbb-exporter     | ----------------------------------------
> bbb-exporter     | 2020-07-09 01:38:25,635 [INFO]: Collecting metrics from BigBlueButton API
> bbb-exporter     | 2020-07-09 01:38:32,497 [INFO]: Finished collecting metrics from BigBlueButton API
> bbb-exporter     | ----------------------------------------
> bbb-exporter     | Exception happened during processing of request from ('127.0.0.1', 48190)
> bbb-exporter     | Traceback (most recent call last):
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
> bbb-exporter     |     self.finish_request(request, client_address)
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
> bbb-exporter     |     self.RequestHandlerClass(request, client_address, self)
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
> bbb-exporter     |     self.handle()
> bbb-exporter     |   File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
> bbb-exporter     |     self.handle_one_request()
> bbb-exporter     |   File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
> bbb-exporter     |     method()
> bbb-exporter     |   File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 159, in do_GET
> bbb-exporter     |     self.wfile.write(output)
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
> bbb-exporter     |     self._sock.sendall(b)
> bbb-exporter     | BrokenPipeError: [Errno 32] Broken pipe

 Prometheus **bbb_node_exporter** target is up. But **bbb** target is down with error:

> Get http://localhost:9688/metrics: context deadline exceeded

I don’t understand which solution helped @lonesomewalker

**Comment by greenstatic** [comment]
I don't know what caused the Broken pipe error, but maybe first try a `sudo docker-compose restart`.

I think @lonesomewalker simply changed the `prometheus.yaml` targets from`localhost` to `127.0.0.1`.

**Comment by Kelivan** [comment]
As I understand it, this error occurs when requesting to bbb_node_exporter (not from). Requests come from prometheus since he does not receive data. What is the difference between targets bbb_node_exporter and bbb? Whay bbb is down?
![image](https://user-images.githubusercontent.com/2749772/87130159-22ee8d80-c29b-11ea-85fd-add5ab9eeaa4.png)

**Comment by lonesomewalker** [comment]
What does your DNS settings say?
Does your server have IPv6 and IPv4? Or one of them only?

**Comment by greenstatic** [comment]
I am assuming you are running the all in one monitoring stack on the same host as the BBB server.

One important thing to note is that you cannot connect to the BBB server from the exporter using localhost (or 127.0.0.1) even though you are on the same physical host. Docker creates a separate network in which localhost means the docker composes network and not the host's network stack. Your best bet is to use the external DNS within the exporter config ([API_BASE_URL](https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/#3-add-your-secrets)) and configure your host to be aware of the external DNS so that you can resolve it locally (as not to create unnecessary external DNS traffic).

**Comment by Kelivan** [comment]
I solved the problem!
The problem was not in the network settings. I just increased scrape_timeout.

> global:
>    scrape_interval: 30s
>    evaluation_interval: 30s
>    scrape_timeout: 30s

I started experimenting with сurl to understand if there were any answers from the exporter at all and noticed that he answered for a very long time, about 20 seconds.

**Comment by greenstatic** [comment]
If your scrape time was so long, you probably don’t have the optimization turned on (https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations)

If you have the all in one monitoring stack on the same host as the bbb server you can enable it very easily. It should dramatically decrease the scrape time (you probably have many recordings): https://github.com/greenstatic/bigbluebutton-exporter/blob/4c2314c0d3b0b66fc9dcb4281c7f23bcaaa2959f/extras/docker-compose.exporter.yaml#L9-L13

I’ll add the optimization (commented out) to the docker-compose file for the all in one monitoring stack and mention it in the docs.

Thanks for the reply!

**Comment by Kelivan** [comment]
@greenstatic Thank you very much for the help! You do a greate jobe!
I turned on optimization and the answers became less than 1 second.
In the picture, the time of requests before enabling optimization:
![image](https://user-images.githubusercontent.com/2749772/87524142-7a706d00-c690-11ea-8477-fcfef480de4b.png)
